# Generated by Django 3.2.6 on 2021-09-15 11:18

import catalogapp.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Наименование')),
                ('title_en', models.CharField(blank=True, max_length=150, verbose_name='Наименование на английском')),
                ('description', models.TextField(blank=True, max_length=2048, verbose_name='Описание')),
                ('description_en', models.TextField(blank=True, max_length=2048, verbose_name='Описание на английском')),
                ('meta_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name')),
                ('meta_description', models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description')),
                ('good_type', models.CharField(blank=True, max_length=150, null=True, verbose_name='Тип')),
                ('good_lenght', models.CharField(blank=True, max_length=150, null=True, verbose_name='Длина')),
                ('good_height', models.CharField(blank=True, max_length=150, null=True, verbose_name='Высота')),
                ('good_depth', models.CharField(blank=True, max_length=150, null=True, verbose_name='Глубина')),
                ('operating_pressure', models.CharField(blank=True, max_length=150, null=True, verbose_name='Рабочее давление')),
                ('test_pressure', models.CharField(blank=True, max_length=150, null=True, verbose_name='Испытательное давление')),
                ('coolant_temperature', models.CharField(blank=True, max_length=150, null=True, verbose_name='Максимальная температура теплоносителя')),
                ('rf_certificate', models.CharField(blank=True, max_length=150, null=True, verbose_name='Сертификат соответствия РФ')),
                ('color', models.CharField(blank=True, max_length=150, null=True, verbose_name='Цвет')),
                ('surface_treatment_technology', models.CharField(blank=True, max_length=150, null=True, verbose_name='Технология обработки поверхности')),
                ('guarantee', models.CharField(blank=True, max_length=150, null=True, verbose_name='Гарантия')),
                ('category', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalogapp.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150, verbose_name='Наименование')),
                ('slug', models.SlugField(blank=True, max_length=36, verbose_name='Url')),
                ('images', models.ImageField(default=None, upload_to=catalogapp.models.get_image_name, verbose_name='Изображение 550x685')),
                ('main_image', models.BooleanField(default=False, verbose_name='Основная картинка')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalogapp.good', verbose_name='Товар')),
            ],
            options={
                'verbose_name': 'Картинка',
                'verbose_name_plural': 'Картинки',
            },
        ),
    ]
