# Generated by Django 3.2.6 on 2021-09-15 14:43

import catalogapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0002_good_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='cpu_slug',
            field=models.SlugField(blank=True, max_length=70, verbose_name='ЧПУ_Url'),
        ),
        migrations.AlterField(
            model_name='picture',
            name='images',
            field=models.ImageField(default=None, upload_to=catalogapp.models.get_image_name_for_product, verbose_name='Изображение 369x419'),
        ),
    ]
