# Generated by Django 3.2.6 on 2021-09-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0003_auto_20210915_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='title_en',
            field=models.CharField(blank=True, max_length=150, verbose_name='Наименование на английском'),
        ),
    ]
