# Generated by Django 3.2.6 on 2021-09-28 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogapp', '0005_auto_20210927_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description_en',
            field=models.TextField(blank=True, max_length=2048, verbose_name='Описание на английском'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_description_en',
            field=models.TextField(blank=True, max_length=1024, null=True, verbose_name='meta description'),
        ),
        migrations.AddField(
            model_name='category',
            name='meta_name_en',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='meta name'),
        ),
    ]
